
//
export const LOCALE_ENGLISH = 'en'
export const LOCALE_CHINESE = 'zh'
export const LOCALE_UPDATE_SUCCESS = 'LOCALE_UPDATE_SUCCESS'

//
export const INDEX_PANEL_TRANSITION_DURATION = 1

//
export const INDEX_OVERLAY_KEY_DESIGN = 'INDEX_OVERLAY_KEY_DESIGN'
export const INDEX_OVERLAY_KEY_INTERIORS = 'INDEX_OVERLAY_KEY_INTERIORS'
export const INDEX_OVERLAY_KEY_PUBLICART = 'INDEX_OVERLAY_KEY_PUBLICART'
