
//
export const LOCALE_UPDATE = 'LOCALE_UPDATE'
export const LOCALE_ENGLISH = 'LOCALE_ENGLISH'
export const LOCALE_CHINESE = 'LOCALE_CHINESE'

//
export const UI_HEADER_THEME_WHITE = 'white'
export const UI_HEADER_THEME_BLUE = 'blue'
export const UI_UPDATE_HEADER_THEME_SUCCESS = 'UI_UPDATE_HEADER_THEME_SUCCESS'

//
export const INDEX_PANEL_TRANSITION_DURATION = 1

//
export const INDEX_OVERLAY_KEY_DESIGN = 'INDEX_OVERLAY_KEY_DESIGN'
export const INDEX_OVERLAY_KEY_INTERIORS = 'INDEX_OVERLAY_KEY_INTERIORS'
export const INDEX_OVERLAY_KEY_PUBLICART = 'INDEX_OVERLAY_KEY_PUBLICART'
export const INDEX_OVERLAY_KEY_HOMES = 'INDEX_OVERLAY_KEY_HOMES'
export const INDEX_OVERLAY_KEY_BRENTWOOD = 'INDEX_OVERLAY_KEY_BRENTWOOD'
export const INDEX_OVERLAY_KEY_ENQUIRE = 'INDEX_OVERLAY_KEY_ENQUIRE'
export const INDEX_OVERLAY_KEY_HOME = 'INDEX_OVERLAY_KEY_HOME'
